# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
matrix:
  include:
  - r: devel
  - r: release
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    after_success:
      - Rscript -e 'covr::codecov()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
      skip_cleanup: true
  - r: 3.6
